[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "11.0.0"
